baseURL: 'https://parohiaparculcalarasi.ro'
title: Parohia Parcul Călărași, Biserica „Sfinții Împărați Constantin și Elena” și „Sfânta Cuvioasă Parascheva”
theme: hugo-theme-bootstrap
copyright: '© {year} Parohia Parcul Călărași. Toate drepturile rezervate.'
defaultContentLanguage: ro
# hasCJKLanguage: true # Uncomment it if your content contains Chinese/Japanese/Korean Languages.
# defaultContentLanguageInSubdir: true
# disableLanguages:
#  - fr
#  - zh-cn
#  - zh-tw
paginate: 10
# paginatePath: page
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true
googleAnalytics: G-3BB0WZWR4M
disqusShortname: parohiaparculcalarasi

blackfriday:
  hrefTargetBlank: true

taxonomies:
  category: categories
  series: series
  tag: tags
  authors: authors
  year: year
  month: month

build:
  writeStats: true

permalinks:
  news: /news/:year/:month/:title/

# module:
  # proxy: https://goproxy.cn

markup:
  goldmark:
    renderer:
      unsafe: true

params:
    author:
      name: Parohia Parcul Călărași
      email: contact@parohiaparculcalarasi.ro
      # avatar: images/profile.png # Avatar image. Default to "images/profile.webp".
      bio: 'Biserica „Sfinții Împărați Constantin și Elena” și „Sfânta Cuvioasă Parascheva”'
      #company: Company # HTML markup are supported, such as: <a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>.
      #location: Bd. Basarabia nr. 2, Sector 2, București, România # HTML markup are supported, such as: <a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>.
      location: București # HTML markup are supported, such as: <a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>.
    social:
      email: contact@parohiaparculcalarasi.ro