ro:
  languageName: Română
  weight: 1
  params:
    dateFormat: 02-01-2006
    description: Parohia Parcul Călărași, Biserica „Sfinţii Împăraţi Constantin şi Elena” şi „Sfânta Cuvioasă Parascheva”
    keywords: Dumnezeu, Parohia Parcul Călărași, Biserica Sfinţii Împăraţi Constantin şi Elena şi Sfânta Cuvioasă Parascheva
    archive:
      dateFormat: 2 January

en:
  languageName: English
  weight: 1

#zh-cn:
#  languageName: 简体中文
#  weight: 4
#  params:
#    dateFormat: '2006-01-02'
#    description: 一个快速、响应式和功能丰富的 Hugo 博客主题
#    keywords: 'Hugo, Bootstrap, 博客主题'
#    archive:
#      dateFormat: 01-02
